routes/admin.php
<?
Route::name('admin.')->group(function () {
  Route::get('/', 'Admin\AuthController@index')->name('login_fr');
  Route::post('/login', 'Admin\AuthController@login')->name('do_login');
  Route::get('/logout', 'Admin\AuthController@logout')->name('do_logout');

  Route::post('/getCity', 'Admin\AdminLocationController@getCity')->name('getCity');
  Route::post('/getPosition', 'Admin\AdminBannerController@getPosition')->name('getBannerPosition');
});

Route::name('admin.')->middleware('auth.admin')->group(function () { 
	Route::get('/dashboard', 'Admin\AdminHomeController@index')->name('dashboard');
	Route::resource('user', 'Admin\AdminUserController');

	Route::resource('category', 'Admin\AdminCategoryController');
	Route::post('category/ajax-load-parent', 'Admin\AdminCategoryController@loadParent');

	Route::name('staff.')->prefix('staff')->group(function () {
		Route::get('/', 'Admin\AdminUserController@index')->name('index');
		Route::any('/create', 'Admin\AdminUserController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminUserController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminUserController@update')->name('edit.update')->where('id', '[0-9]+');
		Route::post('/{id?}/delete', 'Admin\AdminUserController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminUserController@upload')->name('create.upload');
  }); 

	Route::name('configuration.')->prefix('configuration')->group(function () {
		Route::get('/', 'Admin\AdminConfigController@index')->name('index');
		Route::post('/update', 'Admin\AdminConfigController@update')->name('update');
	});

	Route::name('positionBanner.')->prefix('positionBanner')->group(function () {
		Route::get('/', 'Admin\AdminBannerPositionController@index')->name('index');
		Route::any('/create', 'Admin\AdminBannerPositionController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminBannerPositionController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminBannerPositionController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::any('/{id?}/delete', 'Admin\AdminBannerPositionController@destroy')->name('delete')->where('id', '[0-9]+');
	}); 

	Route::name('banner.')->prefix('banner')->group(function () {
		Route::get('/', 'Admin\AdminBannerController@index')->name('index');
		Route::any('/create', 'Admin\AdminBannerController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminBannerController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminBannerController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminBannerController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminBannerController@upload')->name('create.upload');
	}); 

	Route::name('news.')->prefix('news')->group(function () {
		Route::get('/', 'Admin\AdminNewsController@index')->name('index');
		Route::any('/create', 'Admin\AdminNewsController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminNewsController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminNewsController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete/{page?}', 'Admin\AdminNewsController@destroy')->name('delete')->where('id', '[0-9]+')->where('page', '[0-9]+');
		Route::post('/upload', 'Admin\AdminNewsController@upload')->name('create.upload');
	});

	Route::name('campaign.')->prefix('campaign')->group(function () {
		Route::get('/', 'Admin\AdminCampaignController@index')->name('index');
		Route::any('/create', 'Admin\AdminCampaignController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminCampaignController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminCampaignController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminCampaignController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminCampaignController@upload')->name('create.upload');
	}); 

	Route::name('event.')->prefix('event')->group(function () {
		Route::get('/', 'Admin\AdminEventController@index')->name('index');
		Route::any('/create', 'Admin\AdminEventController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminEventController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminEventController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminEventController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminEventController@upload')->name('create.upload');
	}); 

	Route::name('artist.')->prefix('artist')->group(function () {
		Route::get('/', 'Admin\AdminArtistController@index')->name('index');
		Route::any('/create', 'Admin\AdminArtistController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminArtistController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminArtistController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminArtistController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminArtistController@upload')->name('create.upload');
	});

	Route::name('product.')->prefix('product')->group(function () {
		Route::get('/', 'Admin\AdminProductController@index')->name('index');
		Route::any('/create', 'Admin\AdminProductController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminProductController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminProductController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::post('/{id?}/delete', 'Admin\AdminProductController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminProductController@upload')->name('create.upload');

		Route::any('/addMusic', 'Admin\AdminProductController@addMusic')->name('addMusic');
	});

	Route::name('order.')->prefix('order')->group(function () {
		Route::get('/', 'Admin\AdminOrdersController@index')->name('index'); 
		Route::get('/{id?}/delete', 'Admin\AdminOrdersController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::get('/{id?}/confirm', 'Admin\AdminOrdersController@confirm')->name('confirm')->where('id', '[0-9]+');
	});

});
?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'LoginController@login')->name('userLogin');
Route::post('/userActLogin', 'LoginController@actLogin')->name('userActLogin');

Route::middleware(['auth.user'])->group(function () {
  Route::get('/', 'HomeController@index')->name('home');

  Route::get('/intro', 'HomeController@introduction')->name('intro');

  Route::get('/article', 'CampaignController@index')->name('campaign');
  Route::get('/article/{id}-{alias?}', 'CampaignController@detail')->name('campaignDetail');

  Route::get('/artist', 'ArtistController@index')->name('artist');
  Route::get('/artist/{id}-{alias?}', 'ArtistController@detail')->name('artistDetail');

  Route::get('/event', 'EventController@index')->name('event');

  Route::get('/news', 'NewsController@index')->name('news');
  Route::get('/news/{id}-{alias?}', 'NewsController@detail')->name('newsDetail');

  Route::get('/album', 'AlbumController@index')->name('album');
  Route::get('/single/{id?}', 'AlbumController@albumDetail')->name('albumDetail');

  Route::get('/store', 'StoreController@index')->name('store');
  Route::get('/store/{id?}', 'StoreController@product')->name('storeProduct');
  Route::post('/addtocart', 'StoreController@addToCart')->name('addToCart');
  Route::post('/submitOrder', 'StoreController@submitOrder')->name('submitOrder');

  Route::get('/order', 'StoreController@order')->name('order');
  Route::get('/orderSuccess', 'StoreController@orderSuccess')->name('orderSuccess');
    
});

Route::get('404',function(){
  return view('404');
});

Route::get('access_denied',function(){
  return view('pageError');
})->name('access_denied');

resources/views/admin/module/product/add.blade.php
@extends('admin.layouts')
@section('CONTAINER')

<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.product.index')}}"> Sản phẩm</a>
      <span class="breadcrumb-item active">Thêm mới</span>
    </nav>
</div>
<div class="br-pagetitle">
	<h4>Thêm mới  Sản phẩm</h4>
</div>

<div class="br-pagebody">
	<section class="listing-container">
	    <div class="br-section-wrapper container-fluid">
            @include("admin.error")
            <form role="form" method="post" action="{{route('admin.product.create')}}" enctype="multipart/form-data">
            	@csrf  
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Ngôn ngữ</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('lang_id', $arrLang, old('lang_id') ? old('lang_id') : null, ['class="form-control frm_select_2"']); !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Thể loại</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('pro_type', $arrType, old('pro_type') ? old('pro_type') : null, ['class="form-control frm_select_2"']); !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Nghệ sĩ</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('pro_artist_id', $arrArtist, old('pro_artist_id') ? old('pro_artist_id') : null, ['class="form-control frm_select_2"']); !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Tên sản phẩm (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
	                    {!! Form::text('pro_name', old('pro_name') ? old('pro_name') : null, ['class' => 'form-control','placeholder' => 'Nhập tên sản phẩm']) !!}
	                </div>
                </div>           
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Năm xuất bản</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('pro_date', old('pro_date') ? old('pro_date') : null, ['class' => 'form-control']) !!}
                    </div>
                </div> 
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="exampleInputFile">Ảnh đại diện (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="pro_image" id="pro_image" value="{{ old('pro_image') }}">
                        @component('admin.upload', ['id_upload' => 'gallery_upload_file', 'type_upload' => 'product', 'max_upload' => 10, 'multiple' => true ,'item_upload' => 'pro_image', 'name_data' => 'picture_data'])
                        @endcomponent
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Link video</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('pro_link_video', old('pro_link_video') ? old('pro_link_video') : null, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Mô tả ngắn</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('pro_content', old('pro_content') ? old('pro_content') : null, ['class' => 'form-control','placeholder' => 'Nhập mô tả','style="height:100px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Nội dung (*)</label>
                    <div class="col-sm-10 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('pro_detail', old('pro_detail') ? old('pro_detail') : null, ['class' => 'form-control','id' => 'editor1','rows="3"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Giá bán</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
	                    {!! Form::text('pro_price', old('pro_price') ? old('pro_price') : null, ['class' => 'form-control','placeholder' => '0']) !!}
	                </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Số lượng</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('pro_amount', old('pro_amount') ? old('pro_amount') : null, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Sale</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('pro_sale', '1', old('pro_sale') ? true : false, ['class' => 'custom-control-input', 'id' => 'pro_sale']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="pro_sale"></label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Nổi bật</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('pro_hot', '1', old('pro_hot') ? true : false, ['class' => 'custom-control-input', 'id' => 'pro_hot']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="pro_hot"></label>
                        </div>
                    </div>
                </div> 
                <div class="row">
                    <label class="col-sm-2 form-control-label">Kích hoạt</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('pro_status', '1', old('pro_status') ? true : false, ['class' => 'custom-control-input', 'id' => 'pro_status']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="pro_status"></label>
                        </div>
                    </div>
                </div>                
                <!-- /.card-body -->
                <div class="row mg-t-20">
                	<div class="col-sm-2 mg-b-10"></div>
                	<div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="action" value="insert">
	                	<button type="reset" class="btn btn-warning mg-r-20">Làm lại</button>
	                    <button type="submit" class="btn btn-primary">Thêm mới</button>
	                </div>
                </div>
            </form>
        </div>
    </section>
</div>

@endsection

@section('JS_FOOTER')
    <script src="{{ asset('/assets/ckeditorStandard/ckeditor.js') }}"></script>    
    <script>
    CKEDITOR.replace( 'editor1', {
        filebrowserBrowseUrl: '{{ route('ckfinder_browser') }}',
    } );
    </script>
    @include('ckfinder::setup')
    
    <script type="text/javascript">
        var urlUpload = '{{ route("admin.product.create.upload")}}';
    </script>
    <script>
    $(function() {
        $('.frm_select_2').select2();
        $(".select_type").on('change', function(){
            let id = $(this).val();
            if(id == 41){
                $("#box_show_services").show();
            }else{
                $("#box_show_services").hide();
            }
        });
    });
    </script>
@endsection

resources/views/admin/module/product/addMusic.blade.php
@extends('admin.layouts')
@section('CONTAINER')

<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.product.index')}}">Album</a>
      <span class="breadcrumb-item active">Thêm nội dung album</span>
    </nav>
</div>
<div class="br-pagetitle">
	<h4>Thêm mới nội dung album</h4>
</div>

<div class="br-pagebody">
	<section class="listing-container">
	    <div class="br-section-wrapper container-fluid">
            @include("admin.error")
            <form role="form" method="post" action="{{route('admin.product.addMusic')}}" enctype="multipart/form-data">
            	@csrf   
                <div class="row">
                    <label class="col-sm-1 form-control-label" for="InputParent">Album</label>
                    <div class="col-sm-3 mg-b-10 mg-sm-b-10">
                        {!! Form::select('albv_album_id', $albums, old('albv_album_id') ? old('albv_album_id') : null, ['class="form-control frm_select_2"']); !!}
                    </div>
                    <div class="col-sm-3 mg-b-10 mg-sm-b-10">
                        <div class="btn btn-primary" id="addSong">Thêm bài hát</div>
                    </div>
                </div> 
                <div id="listSongToAdd">
                    <div class="row" id="box_add_song">
                        <label class="col-sm-1 form-control-label" for="InputUsername">Bài hát</label>
                        <div class="col-sm-3 mg-b-10 mg-sm-b-10">
    	                    {!! Form::text('albv_title[]', old('albv_title[]') ? old('albv_title[]') : null, ['class' => 'form-control','placeholder' => 'Nhập tên bài hát']) !!}
    	                </div>
                        <div class="col-sm-3 mg-b-10 mg-sm-b-10">
                            {!! Form::text('albv_itunes[]', old('albv_itunes[]') ? old('albv_itunes[]') : null, ['class' => 'form-control','placeholder' => 'Link itunes']) !!}
                        </div>
                        <div class="col-sm-3 mg-b-10 mg-sm-b-10">
                            {!! Form::text('albv_spotify[]', old('albv_spotify[]') ? old('albv_spotify[]') : null, ['class' => 'form-control','placeholder' => 'Link spotify']) !!}
                        </div>
                    </div> 
                </div>
                                
                <!-- /.card-body -->
                <div class="row mg-t-20">
                	<div class="col-sm-2 mg-b-10"></div>
                	<div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="action" value="addMusic">
	                	<button type="reset" class="btn btn-warning mg-r-20">Hủy</button>
	                    <button type="submit" class="btn btn-primary">Xác nhận</button>
	                </div>
                </div>
            </form>
        </div>
    </section>
</div>

@endsection

@section('JS_FOOTER')
    <script src="{{ asset('/assets/ckeditorStandard/ckeditor.js') }}"></script>    
    <script>
    CKEDITOR.replace( 'editor1', {
        filebrowserBrowseUrl: '{{ route('ckfinder_browser') }}',
    } );
    </script>
    @include('ckfinder::setup')
    
    <script type="text/javascript">
        var urlUpload = '{{ route("admin.product.create.upload")}}';
    </script>
    <script>
    $(function() {
        $('.frm_select_2').select2();
        $(".select_type").on('change', function(){
            let id = $(this).val();
            if(id == 41){
                $("#box_show_services").show();
            }else{
                $("#box_show_services").hide();
            }
        });

        $("#addSong").on('click', function(event) {
            event.preventDefault();
            /* Act on the event */
            let box_add_song = $('#box_add_song').clone();
            $("#listSongToAdd").append(box_add_song);
        });
    });
    </script>
@endsection

resources/views/admin/module/product/edit.blade.php
@extends('admin.layouts') 
@section('CONTAINER')


<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.product.index')}}">Sản phẩm</a>
      <span class="breadcrumb-item active">Sửa</span>
    </nav>
</div>
<div class="br-pagetitle">
    <h4>Sửa sản phẩm:  {{ $product['pro_name'] }}</h4>
</div>

<div class="br-pagebody">
    <section class="listing-container">
        <div class="br-section-wrapper container-fluid">
            @include("admin.error")
            <form role="form" method="post" action="/admin/product/{{ $product['pro_id'] }}/edit" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Ngôn ngữ</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('lang_id', $arrLang, old('lang_id') ? old('lang_id') : $product['lang_id'] ?? null, ['class="form-control frm_select_2"']); !!}
                    </div>
                </div>   
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Thể loại</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('pro_type', $arrType, old('pro_type') ? old('pro_type') : $product['pro_type'] ?? null, ['class="form-control frm_select_2"']); !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Nghệ sĩ</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('pro_artist_id', $arrArtist, old('pro_artist_id') ? old('pro_artist_id') : $product['pro_artist_id'] ?? null, ['class="form-control frm_select_2"']); !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Tên sản phẩm (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('pro_name', old('pro_name') ? old('pro_name') : $product['pro_name'] ?? null, ['class' => 'form-control','placeholder' => 'Nhập tên sản phẩm']) !!}
                    </div>
                </div>         
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Năm xuất bản</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('pro_date', old('pro_date') ? old('pro_date') : $product['pro_date'] ?? null, ['class' => 'form-control']) !!}
                    </div>
                </div>                    
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="exampleInputFile">Ảnh đại diện (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="pro_image" id="pro_image" value="{{ old('pro_image') ? old('pro_image') : $product['pro_image'] ?? null  }}">
                        @component('admin.upload', ['id_upload' => 'gallery_upload_file', 'type_upload' => 'product', 'max_upload' => 10, 'multiple' => true ,'item_upload' => 'pro_image', 'name_data' => 'picture_data'])
                        @endcomponent
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Link video</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('pro_link_video', old('pro_link_video') ? old('pro_link_video') : $product['pro_link_video'] ?? null, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Mô tả ngắn</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('pro_content', old('pro_content') ? old('pro_content') : $product['pro_content'] ?? null, ['class' => 'form-control','placeholder' => 'Nhập từ mô tả','style="height:100px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Nội dung (*)</label>
                    <div class="col-sm-10 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('pro_detail', old('pro_detail') ? old('pro_detail') : $product['pro_detail'] ?? null, ['class' => 'form-control','id' => 'editor1','rows="3"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Giá bán</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('pro_price', old('pro_price') ? old('pro_price') : $product['pro_price'] ?? null, ['class' => 'form-control','placeholder' => '0']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Số lượng</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('pro_amount', old('pro_amount') ? old('pro_amount') : $product['pro_amount'] ?? null, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Sale</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('pro_sale', '1', old('pro_sale') ? true : $product['pro_sale'] ?? false, ['class' => 'custom-control-input', 'id' => 'pro_sale']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="pro_sale"></label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Nổi bật</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('pro_hot', '1', $product['pro_hot'] ? true : false, ['class' => 'custom-control-input', 'id' => 'pro_hot']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="pro_hot"></label>
                        </div>
                    </div>
                </div> 
                <div class="row">
                    <label class="col-sm-2 form-control-label">Kích hoạt</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('pro_status', '1', $product['pro_status'] ? true : false, ['class' => 'custom-control-input', 'id' => 'pro_status']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="pro_status"></label>
                        </div>
                    </div>
                </div>  
                
                <!-- /.card-body -->
                <div class="row mg-t-20">
                    <div class="col-sm-2 mg-b-10"></div>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="action" value="update">
                        <button type="reset" class="btn btn-warning mg-r-20">Làm lại</button>
                        <button type="submit" class="btn btn-primary">Lưu</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</div>

@endsection

@section('JS_FOOTER')
<script src="{{ asset('/assets/ckeditorStandard/ckeditor.js') }}"></script>    
<script>
CKEDITOR.replace( 'editor1', {
    filebrowserBrowseUrl: '{{ route('ckfinder_browser') }}',
} );
</script>
@include('ckfinder::setup')

<script type="text/javascript">
    var urlUpload = '{{ route("admin.product.create.upload")}}';
</script>
<script>
$(function() {
    $('.frm_select_2').select2();
    $(".select_type").on('change', function(){
        let id = $(this).val();
        if(id == 41){
            $("#box_show_services").show();
        }else{
            $("#box_show_services").hide();
        }
    }); 
});
</script>
@endsection