routes/admin.php
<?
Route::name('admin.')->group(function () {
  Route::get('/', 'Admin\AuthController@index')->name('login_fr');
  Route::post('/login', 'Admin\AuthController@login')->name('do_login');
  Route::get('/logout', 'Admin\AuthController@logout')->name('do_logout');

  Route::post('/getCity', 'Admin\AdminLocationController@getCity')->name('getCity');
  Route::post('/getPosition', 'Admin\AdminBannerController@getPosition')->name('getBannerPosition');
});

Route::name('admin.')->middleware('auth.admin')->group(function () { 
	Route::get('/dashboard', 'Admin\AdminHomeController@index')->name('dashboard');
	Route::resource('user', 'Admin\AdminUserController');

	Route::resource('category', 'Admin\AdminCategoryController');
	Route::post('category/ajax-load-parent', 'Admin\AdminCategoryController@loadParent');

	Route::name('staff.')->prefix('staff')->group(function () {
		Route::get('/', 'Admin\AdminUserController@index')->name('index');
		Route::any('/create', 'Admin\AdminUserController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminUserController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminUserController@update')->name('edit.update')->where('id', '[0-9]+');
		Route::post('/{id?}/delete', 'Admin\AdminUserController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminUserController@upload')->name('create.upload');
  }); 

	Route::name('configuration.')->prefix('configuration')->group(function () {
		Route::get('/', 'Admin\AdminConfigController@index')->name('index');
		Route::post('/update', 'Admin\AdminConfigController@update')->name('update');
	});

	Route::name('positionBanner.')->prefix('positionBanner')->group(function () {
		Route::get('/', 'Admin\AdminBannerPositionController@index')->name('index');
		Route::any('/create', 'Admin\AdminBannerPositionController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminBannerPositionController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminBannerPositionController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::any('/{id?}/delete', 'Admin\AdminBannerPositionController@destroy')->name('delete')->where('id', '[0-9]+');
	}); 

	Route::name('banner.')->prefix('banner')->group(function () {
		Route::get('/', 'Admin\AdminBannerController@index')->name('index');
		Route::any('/create', 'Admin\AdminBannerController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminBannerController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminBannerController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminBannerController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminBannerController@upload')->name('create.upload');
	}); 

	Route::name('news.')->prefix('news')->group(function () {
		Route::get('/', 'Admin\AdminNewsController@index')->name('index');
		Route::any('/create', 'Admin\AdminNewsController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminNewsController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminNewsController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete/{page?}', 'Admin\AdminNewsController@destroy')->name('delete')->where('id', '[0-9]+')->where('page', '[0-9]+');
		Route::post('/upload', 'Admin\AdminNewsController@upload')->name('create.upload');
	});

	Route::name('campaign.')->prefix('campaign')->group(function () {
		Route::get('/', 'Admin\AdminCampaignController@index')->name('index');
		Route::any('/create', 'Admin\AdminCampaignController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminCampaignController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminCampaignController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminCampaignController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminCampaignController@upload')->name('create.upload');
	}); 

	Route::name('event.')->prefix('event')->group(function () {
		Route::get('/', 'Admin\AdminEventController@index')->name('index');
		Route::any('/create', 'Admin\AdminEventController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminEventController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminEventController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminEventController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminEventController@upload')->name('create.upload');
	}); 

	Route::name('artist.')->prefix('artist')->group(function () {
		Route::get('/', 'Admin\AdminArtistController@index')->name('index');
		Route::any('/create', 'Admin\AdminArtistController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminArtistController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminArtistController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminArtistController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminArtistController@upload')->name('create.upload');
	});

	Route::name('product.')->prefix('product')->group(function () {
		Route::get('/', 'Admin\AdminProductController@index')->name('index');
		Route::any('/create', 'Admin\AdminProductController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminProductController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminProductController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::post('/{id?}/delete', 'Admin\AdminProductController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminProductController@upload')->name('create.upload');

		Route::any('/addMusic', 'Admin\AdminProductController@addMusic')->name('addMusic');
	});

	Route::name('order.')->prefix('order')->group(function () {
		Route::get('/', 'Admin\AdminOrdersController@index')->name('index'); 
		Route::get('/{id?}/delete', 'Admin\AdminOrdersController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::get('/{id?}/confirm', 'Admin\AdminOrdersController@confirm')->name('confirm')->where('id', '[0-9]+');
	});

});
?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'LoginController@login')->name('userLogin');
Route::post('/userActLogin', 'LoginController@actLogin')->name('userActLogin');

Route::middleware(['auth.user'])->group(function () {
  Route::get('/', 'HomeController@index')->name('home');

  Route::get('/intro', 'HomeController@introduction')->name('intro');

  Route::get('/article', 'CampaignController@index')->name('campaign');
  Route::get('/article/{id}-{alias?}', 'CampaignController@detail')->name('campaignDetail');

  Route::get('/artist', 'ArtistController@index')->name('artist');
  Route::get('/artist/{id}-{alias?}', 'ArtistController@detail')->name('artistDetail');

  Route::get('/event', 'EventController@index')->name('event');

  Route::get('/news', 'NewsController@index')->name('news');
  Route::get('/news/{id}-{alias?}', 'NewsController@detail')->name('newsDetail');

  Route::get('/album', 'AlbumController@index')->name('album');
  Route::get('/single/{id?}', 'AlbumController@albumDetail')->name('albumDetail');

  Route::get('/store', 'StoreController@index')->name('store');
  Route::get('/store/{id?}', 'StoreController@product')->name('storeProduct');
  Route::post('/addtocart', 'StoreController@addToCart')->name('addToCart');
  Route::post('/submitOrder', 'StoreController@submitOrder')->name('submitOrder');

  Route::get('/order', 'StoreController@order')->name('order');
  Route::get('/orderSuccess', 'StoreController@orderSuccess')->name('orderSuccess');
    
});

Route::get('404',function(){
  return view('404');
});

Route::get('access_denied',function(){
  return view('pageError');
})->name('access_denied');

app/Http/Controllers/Api/BannersController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Banners;
use Session;
use Validator;
use App\Helper\ImageManager;
use DB;

class BannersController extends Controller
{
	public function __construct(){

	}

	public function index(Request $request)
	{			
		$bannerType       = config('banner.type');
		$bannerTargetType = config('banner.targetType'); 

		$pos      = $request->get('pos', '');
		$site     = $request->get('site', '');
		$platform = $request->header('platform');

		$return 	= ['status' => 0, 'msg' => '', 'data' => ''];
		$Banners = Banners::where("BAN_ACTIVE", 1);

		if($pos != ''){
			$Banners = $Banners->where("BAN_POSITION", $pos);
		}
		if($site != ''){
			$Banners = $Banners->where("BAN_WEBSITE", $site);
		}

		if($platform == 'ios' || $platform == 'android'){
			$Banners = $Banners->where("BAN_DEVICE", 'mob');
		}else{
			$Banners = $Banners->where("BAN_DEVICE", 'pc');
		}

		$Banners = $Banners->get();

		$info = [];
		foreach ($Banners as $key => $banner) {
			$info[$key]['id']          = $banner->ban_id;
			$info[$key]['title']       = $banner->ban_title;
			$info[$key]['description'] = $banner->ban_description;
			$info[$key]['type']        = ($banner->ban_type == 1) ? 'image' : 'video';
			$info[$key]['url']         = $banner->ban_url_data;
			$info[$key]['url_thump']   = ($banner->ban_type == 1) ? $banner->ban_url_data : $banner->ban_url_data_thump;
			$info[$key]['target_type'] = $banner->ban_target_type;
			$info[$key]['target_id']   = $banner->ban_target_id;
			$info[$key]['target_url']  = $banner->ban_target_url;
			$info[$key]['position']    = $banner->ban_position;
		}

		$return['data'] = $info;
		return $return;
	}

	public function create(Request $request)
	{
		$admin_id    = 1;
		$return      = ['status' => 0, 'msg' => '', 'data' => []];
		 
    	return $return; 
	}

	public function destroy($id, Request $request)
	{		
 		$return = ['msg' => 'Gỡ bài thành công', 'status' => 0, 'data' => []];
		return $return;
	}

	public function detail($id)
	{ 
		$return =  ['msg' => '', 'status' => 0, 'data' => []];

		 
 		return $return;
	}
	
    public function changestatus(Request $request)
    {
    	$id     = intval($request->get('id'));
		$status = intval($request->get('status'));
		$news = Banners::where("ban_id","=",$id);

		if ($news)
		{
			$news->update(['ban_active' => $status] ); 
		}
		$return = ['msg' => 'Update thành công', 'status' => 0, 'data' => []];
		return $return;
    }
}

resources/views/admin/module/banner/add.blade.php
@extends('admin.layouts')
@section('CONTAINER')

<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="">Banner</a>
      <span class="breadcrumb-item active">Thêm mới</span>
    </nav>
</div>
<div class="br-pagetitle">
	<h4>Thêm mới banner</h4>
</div>

<div class="br-pagebody">
	<section class="listing-container">
	    <div class="br-section-wrapper container-fluid">
            @include("admin.error")
            <form role="form" method="post" action="{{ env('APP_PREFIX') ?? '/'}}admin/banner/create" enctype="multipart/form-data">
            	@csrf  
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Vị trí</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('ban_position', $arrPosition, old('ban_position') ? old('ban_position') : null, ['class="form-control"']); !!}
                    </div>
                </div> 
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Loại</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('ban_type', $arrType, old('ban_type') ? old('ban_type') : null, ['class="form-control"']); !!}
                    </div>
                </div>  
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Tên banner (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
	                    {!! Form::text('ban_name', old('ban_name') ? old('ban_name') : null, ['class' => 'form-control','placeholder' => 'Nhập tên banner']) !!}
	                </div>
                </div>  
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Url target</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('ban_target_url', old('ban_target_url') ? old('ban_target_url') : null, ['class' => 'form-control','placeholder' => 'Url target']) !!}
                    </div>
                </div>                
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="exampleInputFile">File</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                      	<input type="hidden" name="ban_picture" id="ban_picture" value="{{ old('ban_picture') }}">
						@component('admin.upload', ['id_upload' => 'gallery_upload_file', 'type_upload' => 'banners', 'max_upload' => 10, 'multiple' => true ,'item_upload' => 'ban_picture', 'name_data' => 'picture_data'])
						@endcomponent
                    </div>
                </div>

                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Thứ tự</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
	                    {!! Form::text('ban_order', old('ban_order') ? old('ban_order') : null, ['class' => 'form-control','placeholder' => '0']) !!}
	                </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Active</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('ban_active', '1', false, ['class' => 'custom-control-input', 'id' => 'ban_active']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="ban_active"></label>
                        </div>
                    </div>
                </div>  
                <!-- /.card-body -->
                <div class="row mg-t-20">
                	<div class="col-sm-2 mg-b-10"></div>
                	<div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="action" value="insert">
	                	<button type="reset" class="btn btn-warning mg-r-20">Làm lại</button>
	                    <button type="submit" class="btn btn-primary">Thêm mới</button>
	                </div>
                </div>
            </form>
        </div>
    </section>
</div>

@endsection

@section('JS_FOOTER')
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <script type="text/javascript">
        var urlUpload = '{{ route("admin.banner.create.upload")}}';
    </script>
@endsection

resources/views/admin/module/banner/edit.blade.php
@extends('admin.layouts') 
@section('CONTAINER')


<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12"> 
      <span class="breadcrumb-item active">Sửa</span>
    </nav>
</div>
<div class="br-pagetitle">
    <h4>Sửa Banner</h4>
</div>

<div class="br-pagebody">
    <section class="listing-container">
        <div class="br-section-wrapper container-fluid">
            @include("admin.error")
            <form role="form" method="POST" action="{{ route('admin.banner.edit.update',['id' => $banner['ban_id']]) }}" enctype="multipart/form-data">
                @csrf  
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Vị trí</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('ban_position', $arrPosition, old('ban_position') ? old('ban_position') : isset($banner) ? $banner['ban_position'] : null, ['class="form-control"']); !!}
                    </div>
                </div> 
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Loại</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('ban_type', $arrType, old('ban_type') ? old('ban_type') : isset($banner) ? $banner['ban_type'] : null, ['class="form-control"']); !!}
                    </div>
                </div>  
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Tiêu đề (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('ban_name', old('ban_name') ? old('ban_name') : isset($banner) ? $banner['ban_name'] : null, ['class' => 'form-control','placeholder' => 'Nhập tiêu đề']) !!}
                    </div>
                </div>  
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Url target</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('ban_target_url', old('ban_target_url') ? old('ban_target_url') : isset($banner) ? $banner['ban_target_url'] : null, ['class' => 'form-control','placeholder' => 'Url target']) !!}
                    </div>
                </div> 
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="exampleInputFile"></label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <img width="100%" src="{{$banner['ban_picture']}}" >
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="exampleInputFile">File</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="ban_picture" id="ban_picture" value="{{ old('ban_picture') }}">
                        @component('admin.upload', ['id_upload' => 'gallery_upload_file', 'type_upload' => 'banners', 'max_upload' => 10, 'multiple' => true ,'item_upload' => 'ban_picture', 'name_data' => 'picture_data'])
                        @endcomponent
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Order</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('ban_order', old('ban_order') ? old('ban_order') : isset($banner) ? $banner['ban_order'] : null, ['class' => 'form-control','placeholder' => '0']) !!}
                    </div>
                </div>  
                <div class="row">
                    <label class="col-sm-2 form-control-label">Active</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('ban_active', '1', isset($banner) ? $banner['ban_active'] : false, ['class' => 'custom-control-input', 'id' => 'ban_active']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="ban_active"></label>
                        </div>
                    </div>
                </div>  
                <!-- /.card-body -->
                <div class="row mg-t-20">
                    <div class="col-sm-2 mg-b-10"></div>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="action" value="update">
                        <button type="reset" class="btn btn-warning mg-r-20">Làm lại</button>
                        <button type="submit" class="btn btn-primary">Cập nhật</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</div>

@endsection

@section('JS_FOOTER')
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script> 
    <script type="text/javascript">
        var urlUpload = '{{ route("admin.banner.create.upload")}}';
    </script> 
@endsection

resources/views/admin/module/banner/positionAdd.blade.php
@extends('admin.layouts')
@section('CONTAINER')

<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.positionBanner.index')}}">Danh sách</a>
      <span class="breadcrumb-item active">Thêm mới</span>
    </nav>
</div>
<div class="br-pagetitle">
	<h4>Thêm mới vị trí banner</h4>
</div>

<div class="br-pagebody">
	<section class="listing-container">
	    <div class="br-section-wrapper container-fluid">
            @include("admin.error")
            <form role="form" method="post" action="{{ env('APP_PREFIX') ?? '/'}}admin/positionBanner/create" enctype="multipart/form-data">
            	@csrf
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Tên vị trí</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
	                    {!! Form::text('banp_name', old('banp_name') ? old('banp_name') : null, ['class' => 'form-control','placeholder' => 'Nhập tên vị trí']) !!}
	                </div>
                </div> 
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Mã vị trí</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('banp_position', old('banp_position') ? old('banp_position') : null, ['class' => 'form-control','placeholder' => 'Nhập mã vị trí']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Mô tả</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('banp_description', old('banp_description') ? old('banp_description') : null, ['class' => 'form-control','placeholder' => 'Mô tả']) !!}
                    </div>
                </div> 
                <!-- /.card-body -->
                <div class="row mg-t-20">
                	<div class="col-sm-2 mg-b-10"></div>
                	<div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="action" value="insert">
	                	<button type="reset" class="btn btn-warning mg-r-20">Làm lại</button>
	                    <button type="submit" class="btn btn-primary">Thêm mới</button>
	                </div>
                </div>
            </form>
        </div>
    </section>
</div>

@endsection

@section('JS_FOOTER')
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript">
        var urlUpload = '{{ route("admin.banner.create.upload")}}';
    </script>
    <script>
    $(function() {
        $('input[name="daterange"]').daterangepicker({
            timePicker: false,
            // startDate: moment().startOf('hour'),
            // endDate: moment().startOf('hour').add(24, 'hour'),
            locale: {
              format: 'DD/M/Y'
            }
        }, function(start, end, label) {
          
        });
    }); 
    </script>
@endsection

resources/views/admin/module/banner/positionEdit.blade.php
@extends('admin.layouts')
@section('CONTAINER')

<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.positionBanner.index')}}">Danh sách</a>
      <span class="breadcrumb-item active">Sửa đổi</span>
    </nav>
</div>
<div class="br-pagetitle">
	<h4>Sửa thông tin vị trí banner</h4>
</div>

<div class="br-pagebody">
	<section class="listing-container">
	    <div class="br-section-wrapper container-fluid">
            @include("admin.error")
            <form role="form" method="post" action="{{ route('admin.positionBanner.edit', ['id' => $banPos['banp_id']]) }}" enctype="multipart/form-data">
            	@csrf
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Tên vị trí</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
	                    {!! Form::text('banp_name', old('banp_name') ? old('banp_name') : isset($banPos) ? $banPos['banp_name'] : null, ['class' => 'form-control','placeholder' => 'Nhập tên vị trí']) !!}
	                </div>
                </div> 
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Mã vị trí</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('banp_position', old('banp_position') ? old('banp_position') : isset($banPos) ? $banPos['banp_position'] : null, ['class' => 'form-control','placeholder' => 'Nhập mã vị trí']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Mô tả</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('banp_description', old('banp_description') ? old('banp_description') : isset($banPos) ? $banPos['banp_description'] : null, ['class' => 'form-control','placeholder' => 'Mô tả']) !!}
                    </div>
                </div> 
                <!-- /.card-body -->
                <div class="row mg-t-20">
                	<div class="col-sm-2 mg-b-10"></div>
                	<div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="action" value="update">
	                	<button type="reset" class="btn btn-warning mg-r-20">Làm lại</button>
	                    <button type="submit" class="btn btn-primary">Cập nhật</button>
	                </div>
                </div>
            </form>
        </div>
    </section>
</div>

@endsection

@section('JS_FOOTER')
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>

    <script type="text/javascript">
        var urlUpload = '{{ route("admin.banner.create.upload")}}';
    </script>
    <script>
    $(function() {
        $('input[name="daterange"]').daterangepicker({
            timePicker: false,
            // startDate: moment().startOf('hour'),
            // endDate: moment().startOf('hour').add(24, 'hour'),
            locale: {
              format: 'DD/M/Y'
            }
        }, function(start, end, label) {
          
        });
    }); 
    </script>
@endsection