routes/admin.php
<?
Route::name('admin.')->group(function () {
  Route::get('/', 'Admin\AuthController@index')->name('login_fr');
  Route::post('/login', 'Admin\AuthController@login')->name('do_login');
  Route::get('/logout', 'Admin\AuthController@logout')->name('do_logout');

  Route::post('/getCity', 'Admin\AdminLocationController@getCity')->name('getCity');
  Route::post('/getPosition', 'Admin\AdminBannerController@getPosition')->name('getBannerPosition');
});

Route::name('admin.')->middleware('auth.admin')->group(function () { 
	Route::get('/dashboard', 'Admin\AdminHomeController@index')->name('dashboard');
	Route::resource('user', 'Admin\AdminUserController');

	Route::resource('category', 'Admin\AdminCategoryController');
	Route::post('category/ajax-load-parent', 'Admin\AdminCategoryController@loadParent');

	Route::name('staff.')->prefix('staff')->group(function () {
		Route::get('/', 'Admin\AdminUserController@index')->name('index');
		Route::any('/create', 'Admin\AdminUserController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminUserController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminUserController@update')->name('edit.update')->where('id', '[0-9]+');
		Route::post('/{id?}/delete', 'Admin\AdminUserController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminUserController@upload')->name('create.upload');
  }); 

	Route::name('configuration.')->prefix('configuration')->group(function () {
		Route::get('/', 'Admin\AdminConfigController@index')->name('index');
		Route::post('/update', 'Admin\AdminConfigController@update')->name('update');
	});

	Route::name('positionBanner.')->prefix('positionBanner')->group(function () {
		Route::get('/', 'Admin\AdminBannerPositionController@index')->name('index');
		Route::any('/create', 'Admin\AdminBannerPositionController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminBannerPositionController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminBannerPositionController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::any('/{id?}/delete', 'Admin\AdminBannerPositionController@destroy')->name('delete')->where('id', '[0-9]+');
	}); 

	Route::name('banner.')->prefix('banner')->group(function () {
		Route::get('/', 'Admin\AdminBannerController@index')->name('index');
		Route::any('/create', 'Admin\AdminBannerController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminBannerController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminBannerController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminBannerController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminBannerController@upload')->name('create.upload');
	}); 

	Route::name('news.')->prefix('news')->group(function () {
		Route::get('/', 'Admin\AdminNewsController@index')->name('index');
		Route::any('/create', 'Admin\AdminNewsController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminNewsController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminNewsController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete/{page?}', 'Admin\AdminNewsController@destroy')->name('delete')->where('id', '[0-9]+')->where('page', '[0-9]+');
		Route::post('/upload', 'Admin\AdminNewsController@upload')->name('create.upload');
	});

	Route::name('campaign.')->prefix('campaign')->group(function () {
		Route::get('/', 'Admin\AdminCampaignController@index')->name('index');
		Route::any('/create', 'Admin\AdminCampaignController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminCampaignController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminCampaignController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminCampaignController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminCampaignController@upload')->name('create.upload');
	}); 

	Route::name('event.')->prefix('event')->group(function () {
		Route::get('/', 'Admin\AdminEventController@index')->name('index');
		Route::any('/create', 'Admin\AdminEventController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminEventController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminEventController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminEventController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminEventController@upload')->name('create.upload');
	}); 

	Route::name('artist.')->prefix('artist')->group(function () {
		Route::get('/', 'Admin\AdminArtistController@index')->name('index');
		Route::any('/create', 'Admin\AdminArtistController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminArtistController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminArtistController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminArtistController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminArtistController@upload')->name('create.upload');
	});

	Route::name('product.')->prefix('product')->group(function () {
		Route::get('/', 'Admin\AdminProductController@index')->name('index');
		Route::any('/create', 'Admin\AdminProductController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminProductController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminProductController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::post('/{id?}/delete', 'Admin\AdminProductController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminProductController@upload')->name('create.upload');

		Route::any('/addMusic', 'Admin\AdminProductController@addMusic')->name('addMusic');
	});

	Route::name('order.')->prefix('order')->group(function () {
		Route::get('/', 'Admin\AdminOrdersController@index')->name('index'); 
		Route::get('/{id?}/delete', 'Admin\AdminOrdersController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::get('/{id?}/confirm', 'Admin\AdminOrdersController@confirm')->name('confirm')->where('id', '[0-9]+');
	});

});
?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'LoginController@login')->name('userLogin');
Route::post('/userActLogin', 'LoginController@actLogin')->name('userActLogin');

Route::middleware(['auth.user'])->group(function () {
  Route::get('/', 'HomeController@index')->name('home');

  Route::get('/intro', 'HomeController@introduction')->name('intro');

  Route::get('/article', 'CampaignController@index')->name('campaign');
  Route::get('/article/{id}-{alias?}', 'CampaignController@detail')->name('campaignDetail');

  Route::get('/artist', 'ArtistController@index')->name('artist');
  Route::get('/artist/{id}-{alias?}', 'ArtistController@detail')->name('artistDetail');

  Route::get('/event', 'EventController@index')->name('event');

  Route::get('/news', 'NewsController@index')->name('news');
  Route::get('/news/{id}-{alias?}', 'NewsController@detail')->name('newsDetail');

  Route::get('/album', 'AlbumController@index')->name('album');
  Route::get('/single/{id?}', 'AlbumController@albumDetail')->name('albumDetail');

  Route::get('/store', 'StoreController@index')->name('store');
  Route::get('/store/{id?}', 'StoreController@product')->name('storeProduct');
  Route::post('/addtocart', 'StoreController@addToCart')->name('addToCart');
  Route::post('/submitOrder', 'StoreController@submitOrder')->name('submitOrder');

  Route::get('/order', 'StoreController@order')->name('order');
  Route::get('/orderSuccess', 'StoreController@orderSuccess')->name('orderSuccess');
    
});

Route::get('404',function(){
  return view('404');
});

Route::get('access_denied',function(){
  return view('pageError');
})->name('access_denied');

app/Http/Controllers/ArtistController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Cookie;
use DB;
use App\Repositories\ArtistRepository;

class ArtistController extends FrontEndController
{   
    protected $ArtistRepository;
    public function __construct(ArtistRepository $ArtistRepository){
        $this->ArtistRepository = $ArtistRepository;
    }
    public function getType()
    {
     $type = [
         1 => 'Album',
         2 => 'Singles & EPs ',
         3 => 'Fimography'
     ];

     return $type;
    }

    public function index(Request $request){ 
        $listArtist = $this->ArtistRepository->getArtists();
            
        $data = [
            'listArtist' => $listArtist,
        ];
        return view('artist')->with($data);
    }
    
    public function detail(Request $request, $id, $alias = ''){

        $artistInfo = $this->ArtistRepository->getArtistDetail($id);
        $arrType = $this->gettype();

        $images     = $artistInfo['images'] ?? [];
        $products   = $artistInfo['products'] ?? [];
        $arrInfoProduct = [];
        foreach ($products as $value) {
            $arrInfoProduct[$value['pro_type']][] = $value;
        }

        $data = [
            'artistInfo' => $artistInfo, 
            'arrType' => $arrType,
            'arrInfoProduct' => $arrInfoProduct, 
            'arrImages' => $images,
        ];
        
        return view('artistDetail')->with($data);
    }
}

resources/views/admin/module/artist/add.blade.php
@extends('admin.layouts')
@section('CONTAINER')

<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.artist.index')}}">Nghệ sĩ</a>
      <span class="breadcrumb-item active">Thêm mới</span>
    </nav>
</div>
<div class="br-pagetitle">
	<h4>Thêm mới nghệ sĩ</h4>
</div>

<div class="br-pagebody">
	<section class="listing-container">
	    <div class="br-section-wrapper container-fluid">
            @include("admin.error")
            <form role="form" method="post" action="{{route('admin.artist.create')}}" enctype="multipart/form-data">
            	@csrf  
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Ngôn ngữ</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('lang_id', $arrLang, old('lang_id') ? old('lang_id') : null, ['class="form-control frm_select_2"']); !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Lĩnh vực</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('art_job', $arrJob, old('art_job') ? old('art_job') : null, ['class="form-control frm_select_2"']); !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Nghệ danh (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
	                    {!! Form::text('art_name', old('art_name') ? old('art_name') : null, ['class' => 'form-control','placeholder' => 'Nhập tên nghệ sĩ']) !!}
	                </div>
                </div> 
                 <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Năm sinh</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('art_birthday', old('art_birthday') ? old('art_birthday') : null, ['class' => 'form-control','placeholder' => 'Nhập năm sinh']) !!}
                    </div>
                </div> 
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Debut</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('art_year_debut', old('art_year_debut') ? old('art_year_debut') : null, ['class' => 'form-control','placeholder' => 'Nhập năm debut']) !!}
                    </div>
                </div>             
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Spotify</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('art_spotify_url', old('art_spotify_url') ? old('art_spotify_url') : null, ['class' => 'form-control','placeholder' => 'Spotify']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Itunes</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('art_itunes_url', old('art_itunes_url') ? old('art_itunes_url') : null, ['class' => 'form-control','placeholder' => 'Itunes']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="exampleInputFile">Ảnh đại diện (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="art_avatar" id="art_avatar" value="{{ old('art_avatar') }}">
                        @component('admin.upload', ['id_upload' => 'gallery_upload_file', 'type_upload' => 'artist', 'max_upload' => 25, 'multiple' => true ,'item_upload' => 'art_avatar', 'name_data' => 'picture_data'])
                        @endcomponent
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Mô tả ngắn</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('art_intro', old('art_intro') ? old('art_intro') : null, ['class' => 'form-control','placeholder' => 'Nhập mô tả','style="height:100px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Giới thiệu (*)</label>
                    <div class="col-sm-10 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('art_description', old('art_description') ? old('art_description') : null, ['class' => 'form-control','id' => 'editor1','rows="3"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Giải thưởng (*)</label>
                    <div class="col-sm-10 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('art_awards', old('art_awards') ? old('art_awards') : null, ['class' => 'form-control','id' => 'editor2','rows="3"']) !!}
                    </div>
                </div>
                {{-- <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Thứ tự</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
	                    {!! Form::text('art_order', old('art_order') ? old('art_order') : null, ['class' => 'form-control','placeholder' => '0']) !!}
	                </div>
                </div> --}}
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Video</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('art_link_video', old('art_link_video') ? old('art_link_video') : null, ['class' => 'form-control','placeholder' => 'Video youtube','style="height:100px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="exampleInputFile">Background</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="art_background" id="art_background" value="{{ old('art_background') }}">
                        @component('admin.upload', ['id_upload' => 'gallery_upload_background', 'type_upload' => 'artist', 'max_upload' => 1, 'multiple' => false ,'item_upload' => 'art_background', 'name_data' => 'art_background_data'])
                        @endcomponent
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="exampleInputFile">Small picture</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="art_small_pic" id="art_small_pic" value="{{ old('art_small_pic') }}">
                        @component('admin.upload', ['id_upload' => 'gallery_upload_small_pic', 'type_upload' => 'artist', 'max_upload' => 1, 'multiple' => false ,'item_upload' => 'art_small_pic', 'name_data' => 'art_small_pic_data'])
                        @endcomponent
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Facebook</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('art_facebook_link', old('art_facebook_link') ? old('art_facebook_link') : null, ['class' => 'form-control','placeholder' => 'Facebook']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Instagram</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('art_instagram_link', old('art_instagram_link') ? old('art_instagram_link') : null, ['class' => 'form-control','placeholder' => 'Instagram']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Youtube</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('art_youtube_link', old('art_youtube_link') ? old('art_youtube_link') : null, ['class' => 'form-control','placeholder' => 'Youtube']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Twitter</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('art_twitter_link', old('art_twitter_link') ? old('art_twitter_link') : null, ['class' => 'form-control','placeholder' => 'Twitter']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Tiktok</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('art_tiktok_link', old('art_tiktok_link') ? old('art_tiktok_link') : null, ['class' => 'form-control','placeholder' => 'Tiktok']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Nổi bật</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('art_hot', '1', old('art_hot') ? true : false, ['class' => 'custom-control-input', 'id' => 'art_hot']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="art_hot"></label>
                        </div>
                    </div>
                </div> 
                <div class="row">
                    <label class="col-sm-2 form-control-label">Kích hoạt</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('art_active', '1', old('art_active') ? true : false, ['class' => 'custom-control-input', 'id' => 'art_active']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="art_active"></label>
                        </div>
                    </div>
                </div>                
                <!-- /.card-body -->
                <div class="row mg-t-20">
                	<div class="col-sm-2 mg-b-10"></div>
                	<div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="action" value="insert">
	                	<button type="reset" class="btn btn-warning mg-r-20">Làm lại</button>
	                    <button type="submit" class="btn btn-primary">Thêm mới</button>
	                </div>
                </div>
            </form>
        </div>
    </section>
</div>

@endsection

@section('JS_FOOTER')
    <script src="{{ asset('/assets/ckeditorStandard/ckeditor.js') }}"></script>    
    <script>
    CKEDITOR.replace( 'editor1', {
        filebrowserBrowseUrl: '{{ route('ckfinder_browser') }}',
    } );
    CKEDITOR.replace( 'editor2', {
        filebrowserBrowseUrl: '{{ route('ckfinder_browser') }}',
    } );
    </script>
    @include('ckfinder::setup')
    
    <script type="text/javascript">
        var urlUpload = '{{ route("admin.artist.create.upload")}}';
    </script>
    <script>
    $(function() {
        $('.frm_select_2').select2();
        $(".select_type").on('change', function(){
            let id = $(this).val();
            if(id == 41){
                $("#box_show_services").show();
            }else{
                $("#box_show_services").hide();
            }
        });
    });
    </script>
@endsection

resources/views/admin/module/artist/list.blade.php
@extends('admin.layouts')
@section('CONTAINER')
<style type="text/css">
	.listing-container .fa-check-square, .fa-square{
		cursor: pointer;
	}
</style>
<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.artist.index')}}">Nghệ sĩ</a>
      <span class="breadcrumb-item active">Danh sách</span>
    </nav>
</div>
<div class="br-pagetitle">
	<h4>Danh sách Nghệ sĩ</h4>
</div>

<div class="br-pagebody">
	<section class="listing-container">
        <div class="br-section-wrapper container-fluid">
			<h6 class="br-section-label">Tìm kiếm</h6>
  	  		<form method="GET" action="{{ $page_filter_url }}">
  	  			<div class="row">
		            <div class="col-lg">
		              <input class="form-control" name="art_name" placeholder="Tên" type="text" value="{{ isset($params['art_name']) ? $params['art_name'] : '' }}">
		            </div>
		            <div class="col-lg">
		              <select  class="form-control" name="lang_id" >
		              	<option value="-1">Ngôn ngữ</option>
		              	@foreach($arrLang as $key => $value)
		              		<option {{ (isset($params['lang_id']) && $params['lang_id'] == $key) ? 'selected' : '' }}  value="{{$key}}">{{$value}}</option>
		              	@endforeach
		              </select>
		            </div>
		            <div class="col-lg">
		              <select  class="form-control" name="art_job" >
		              	<option value="-1">Nghề nghiệp</option>
		              	@foreach($arrJob as $key => $value)
		              		<option {{ (isset($params['art_job']) && $params['art_job'] == $key) ? 'selected' : '' }}  value="{{$key}}">{{$value}}</option>
		              	@endforeach
		              </select>
		            </div>
								<div class="col-lg">
		              <select  class="form-control" name="art_hot" >
		              	<option value="-1">-Chọn-</option>
		              	@foreach($arrHot as $key => $value)
		              		<option {{ (isset($params['art_hot']) && $params['art_hot'] == $key) ? 'selected' : '' }}  value="{{$key}}">{{$value}}</option>
		              	@endforeach
		              </select>
		            </div>
		            <div class="col-lg">
		              <select  class="form-control" name="art_status" >
		              	<option value="-1">=Kích hoạt=</option>
		              	@foreach($arrStatus as $key => $value)
		              		<option {{ (isset($params['art_status']) && $params['art_status'] == $key) ? 'selected' : '' }}  value="{{$key}}">{{$value}}</option>
		              	@endforeach
		              </select>
		            </div>
		            <div class="col-lg-2 mg-t-10 mg-lg-t-0">
		            	<button class="btn btn-primary btn-block mg-b-10"><i class="fa fa-send mg-r-10"></i>Search</button>
		            </div>
		        </div>
  	    	</form>


		  	<div class="bd rounded table-responsive">
		  	  	<table class="table table-bordered table-striped mg-b-0">
		  	  		<tbody class="">
		                <tr class="thead-colored thead-light">
				          	<td>ID</td>
				          	<td>Tên</td>
				          	<td class="text-center">Avatar</td> 
				          	<td class="text-center">Ngày tạo</td>
				          	<td class="text-center">Nổi bật</td> 
								 <td class="text-center">Sắp xếp</td> 
				          	<td class="text-center">Trạng thái</td>
				          	<td class="text-center">Action</td>
				        </tr>
				      	@foreach ($Artists as $keys => $Artist)
					      	<tr>
							   <td>{{ ++$keys + ($page-1)*15 }}</td>
					           <td>
					           		<p><b>{{ $Artist['art_name'] }}</b></p>
					           		<p>Người tạo: <b>{{ $arrUser[$Artist['admin_id']] ?? 'admin' }}</b></p>
					           		@isset ($arrUser[$Artist['edit_admin']])
					           			<p>Chỉnh sửa: <b>{{ $arrUser[$Artist['edit_admin']] ?? null }}</b></p>    
					           		@endisset					           		
					           </td>
					           <td class="text-center"><img width="100px" src="{{ $Artist['art_avatar'] }}"></td>					            
					           <td class="text-center">{{ date('H:i:s d/m/Y', $Artist['art_create_date'])  }}</td>
					           <td class="text-center">
					          		<i class="far {{($Artist['art_hot'] == 1) ? 'fa-check-square' : 'fa-square' }}" idata="{{$Artist['art_id']}}" onclick="updateHot($(this))"></i>
					           </td>
								  <td class="text-center">
								  		<input class="form-control text-center order_by" idata="{{$Artist['art_id']}}" style="width: 75px; margin: auto;" type="text" value="{{ $Artist['art_order'] }}">
								  </td>
					           <td class="text-center">
					           		<b>
					            	@if($Artist['art_active'] <= 0)
					            		Đợi duyệt
					            	@elseif($Artist['art_active'] == 2)
					            		Không duyệt
					            	@elseif($Artist['art_active'] == 1)
					            		Đã duyệt
					            	@endif
					            	</b>
					           </td>
					           <td class="text-center">
					           		<p><a href="{{ route('admin.artist.edit', ['id' => $Artist['art_id']])  }}"><i class="fas fa-edit"></i> Sửa</a></p>
					           		{!! Form::open(['url' => '/admin/artist/'. $Artist['art_id'].'/delete' , 'method' => 'GET', 'onsubmit' => 'return confirm("Bạn có chắc chắn muốn xóa bản ghi này?")']); !!}
						          		<button type="submit" class="button-delete" style="cursor: pointer;"><i class="fa fa-times-circle"></i> Xóa</button>
					          		{!! Form::close() !!}					          		
					           </td>
							</tr>
				      	@endforeach
		      		</tbody>
		  	  	</table>
            </div>
            <br/>
            {!! $Artists->appends($params)->render() !!}
        </div>
    </section>

</div>
@endsection

@section("JS_FOOTER")
<script type="text/javascript">
	$(function() {	 
		$(".order_by").on('change',function(){
			let id = $(this).attr('idata');
			let val = $(this).val();

			/*Update orrder*/
			$.ajax({
				url: '{{ route('api.change_order.artistChangeOrder') }}',
				type: 'POST',
				dataType: 'JSON',
				data: {id:id, value:val},
				success: function(data){
					if(data.status == 0){
						console.log('success');
					}
				}
			});			
		});
	}); 

	function updateHot(obj){
		let idata = obj.attr('idata');
		$.ajax({
        url: '{{route('api.set_hot.hotArtist')}}',
        type: "POST",
        dataType: 'json',
        data: {idata:idata},
        success: function(html){
         	if(obj.hasClass('fa-check-square')){
         		obj.removeClass('fa-check-square').addClass('fa-square')
         	}else if(obj.hasClass('fa-square')){
         		obj.removeClass('fa-square').addClass('fa-check-square')
         	}  
        }
    });
	}; 
</script>
@endsection