routes/admin.php
<?
Route::name('admin.')->group(function () {
  Route::get('/', 'Admin\AuthController@index')->name('login_fr');
  Route::post('/login', 'Admin\AuthController@login')->name('do_login');
  Route::get('/logout', 'Admin\AuthController@logout')->name('do_logout');

  Route::post('/getCity', 'Admin\AdminLocationController@getCity')->name('getCity');
  Route::post('/getPosition', 'Admin\AdminBannerController@getPosition')->name('getBannerPosition');
});

Route::name('admin.')->middleware('auth.admin')->group(function () { 
	Route::get('/dashboard', 'Admin\AdminHomeController@index')->name('dashboard');
	Route::resource('user', 'Admin\AdminUserController');

	Route::resource('category', 'Admin\AdminCategoryController');
	Route::post('category/ajax-load-parent', 'Admin\AdminCategoryController@loadParent');

	Route::name('staff.')->prefix('staff')->group(function () {
		Route::get('/', 'Admin\AdminUserController@index')->name('index');
		Route::any('/create', 'Admin\AdminUserController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminUserController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminUserController@update')->name('edit.update')->where('id', '[0-9]+');
		Route::post('/{id?}/delete', 'Admin\AdminUserController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminUserController@upload')->name('create.upload');
  }); 

	Route::name('configuration.')->prefix('configuration')->group(function () {
		Route::get('/', 'Admin\AdminConfigController@index')->name('index');
		Route::post('/update', 'Admin\AdminConfigController@update')->name('update');
	});

	Route::name('positionBanner.')->prefix('positionBanner')->group(function () {
		Route::get('/', 'Admin\AdminBannerPositionController@index')->name('index');
		Route::any('/create', 'Admin\AdminBannerPositionController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminBannerPositionController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminBannerPositionController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::any('/{id?}/delete', 'Admin\AdminBannerPositionController@destroy')->name('delete')->where('id', '[0-9]+');
	}); 

	Route::name('banner.')->prefix('banner')->group(function () {
		Route::get('/', 'Admin\AdminBannerController@index')->name('index');
		Route::any('/create', 'Admin\AdminBannerController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminBannerController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminBannerController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminBannerController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminBannerController@upload')->name('create.upload');
	}); 

	Route::name('news.')->prefix('news')->group(function () {
		Route::get('/', 'Admin\AdminNewsController@index')->name('index');
		Route::any('/create', 'Admin\AdminNewsController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminNewsController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminNewsController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete/{page?}', 'Admin\AdminNewsController@destroy')->name('delete')->where('id', '[0-9]+')->where('page', '[0-9]+');
		Route::post('/upload', 'Admin\AdminNewsController@upload')->name('create.upload');
	});

	Route::name('campaign.')->prefix('campaign')->group(function () {
		Route::get('/', 'Admin\AdminCampaignController@index')->name('index');
		Route::any('/create', 'Admin\AdminCampaignController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminCampaignController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminCampaignController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminCampaignController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminCampaignController@upload')->name('create.upload');
	}); 

	Route::name('event.')->prefix('event')->group(function () {
		Route::get('/', 'Admin\AdminEventController@index')->name('index');
		Route::any('/create', 'Admin\AdminEventController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminEventController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminEventController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminEventController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminEventController@upload')->name('create.upload');
	}); 

	Route::name('artist.')->prefix('artist')->group(function () {
		Route::get('/', 'Admin\AdminArtistController@index')->name('index');
		Route::any('/create', 'Admin\AdminArtistController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminArtistController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminArtistController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::get('/{id?}/delete', 'Admin\AdminArtistController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminArtistController@upload')->name('create.upload');
	});

	Route::name('product.')->prefix('product')->group(function () {
		Route::get('/', 'Admin\AdminProductController@index')->name('index');
		Route::any('/create', 'Admin\AdminProductController@create')->name('create');
		Route::get('/{id?}/edit', 'Admin\AdminProductController@edit')->name('edit')->where('id', '[0-9]+');
		Route::post('/{id?}/edit', 'Admin\AdminProductController@edit')->name('edit.update')->where('id', '[0-9]+');
		Route::post('/{id?}/delete', 'Admin\AdminProductController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::post('/upload', 'Admin\AdminProductController@upload')->name('create.upload');

		Route::any('/addMusic', 'Admin\AdminProductController@addMusic')->name('addMusic');
	});

	Route::name('order.')->prefix('order')->group(function () {
		Route::get('/', 'Admin\AdminOrdersController@index')->name('index'); 
		Route::get('/{id?}/delete', 'Admin\AdminOrdersController@destroy')->name('delete')->where('id', '[0-9]+');
		Route::get('/{id?}/confirm', 'Admin\AdminOrdersController@confirm')->name('confirm')->where('id', '[0-9]+');
	});

});
?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'LoginController@login')->name('userLogin');
Route::post('/userActLogin', 'LoginController@actLogin')->name('userActLogin');

Route::middleware(['auth.user'])->group(function () {
  Route::get('/', 'HomeController@index')->name('home');

  Route::get('/intro', 'HomeController@introduction')->name('intro');

  Route::get('/article', 'CampaignController@index')->name('campaign');
  Route::get('/article/{id}-{alias?}', 'CampaignController@detail')->name('campaignDetail');

  Route::get('/artist', 'ArtistController@index')->name('artist');
  Route::get('/artist/{id}-{alias?}', 'ArtistController@detail')->name('artistDetail');

  Route::get('/event', 'EventController@index')->name('event');

  Route::get('/news', 'NewsController@index')->name('news');
  Route::get('/news/{id}-{alias?}', 'NewsController@detail')->name('newsDetail');

  Route::get('/album', 'AlbumController@index')->name('album');
  Route::get('/single/{id?}', 'AlbumController@albumDetail')->name('albumDetail');

  Route::get('/store', 'StoreController@index')->name('store');
  Route::get('/store/{id?}', 'StoreController@product')->name('storeProduct');
  Route::post('/addtocart', 'StoreController@addToCart')->name('addToCart');
  Route::post('/submitOrder', 'StoreController@submitOrder')->name('submitOrder');

  Route::get('/order', 'StoreController@order')->name('order');
  Route::get('/orderSuccess', 'StoreController@orderSuccess')->name('orderSuccess');
    
});

Route::get('404',function(){
  return view('404');
});

Route::get('access_denied',function(){
  return view('pageError');
})->name('access_denied');

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\EventRepository;
use App\Repositories\BannerRepository;
use Cookie;
use DB;

class EventController extends FrontEndController
{   
    protected $EventRepository;
    public function __construct(EventRepository $EventRepository){
        $this->EventRepository = $EventRepository;
    }

    public function index(Request $request){ 
        $BannerRepository = new BannerRepository;
        $banners = $BannerRepository->getBanners(['pos'=>'event_page_banner', 'limit' => 1]);
        
        $page = $request->get('page', 1);

        $listEvent = $this->EventRepository->getEvents([
            'page' => $page - 1,
            'perPage' => 20,
        ]);
        
        //pagination
        $pagination = $this->EventRepository->paging([
            'page'    => $page -1,
            'perPage' => 20,
        ]);
        
        $hotEvent = $listEvent[0];
        unset($listEvent[0]);

        $data = [
            'hotEvent' => $hotEvent,
            'listEvent' => $listEvent,
            'pagination' => $pagination,
            'banners' => $banners,
        ];
        return view('event')->with($data);
    }

}

resources/views/admin/module/event/add.blade.php
@extends('admin.layouts')
@section('CONTAINER')

<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.event.index')}}">Sự kiện</a>
      <span class="breadcrumb-item active">Thêm mới</span>
    </nav>
</div>
<div class="br-pagetitle">
	<h4>Thêm mới Sự kiện</h4>
</div>

<div class="br-pagebody">
	<section class="listing-container">
	    <div class="br-section-wrapper container-fluid">
            @include("admin.error")
            <form role="form" method="post" action="{{route('admin.event.create')}}" enctype="multipart/form-data">
            	@csrf  
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Ngôn ngữ</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('lang_id', $arrLang, old('lang_id') ? old('lang_id') : null, ['class="form-control frm_select_2"']); !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Tiêu đề (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
	                    {!! Form::text('eve_title', old('eve_title') ? old('eve_title') : null, ['class' => 'form-control','placeholder' => 'Nhập tiêu đề']) !!}
	                </div>
                </div>                
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="exampleInputFile">Ảnh đại diện (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="eve_banner" id="eve_banner" value="{{ old('eve_banner') }}">
                        @component('admin.upload', ['id_upload' => 'gallery_upload_file', 'type_upload' => 'event', 'max_upload' => 10, 'multiple' => true ,'item_upload' => 'eve_banner', 'name_data' => 'picture_data'])
                        @endcomponent
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Mô tả ngắn</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('eve_intro', old('eve_intro') ? old('eve_intro') : null, ['class' => 'form-control','placeholder' => 'Nhập mô tả','style="height:100px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Tags</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('eve_tags', old('eve_tags') ? old('eve_tags') : null, ['class' => 'form-control','placeholder' => 'Từ khóa: tu khoa 1| Từ khóa 2| Từ khóa 3','style="height:120px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Form Download</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('eve_form_apply', old('eve_form_apply') ? old('eve_form_apply') : null, ['class' => 'form-control','placeholder' => 'Link form download','style="height:120px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Nội dung (*)</label>
                    <div class="col-sm-10 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('eve_description', old('eve_description') ? old('eve_description') : null, ['class' => 'form-control','id' => 'editor1','rows="3"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Thứ tự</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
	                    {!! Form::text('eve_order', old('eve_order') ? old('eve_order') : null, ['class' => 'form-control','placeholder' => '0']) !!}
	                </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Video</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('eve_video_url', old('eve_video_url') ? old('eve_video_url') : null, ['class' => 'form-control','placeholder' => 'Video youtube','style="height:100px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Kích hoạt</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('eve_status', '1', old('eve_status') ? true : false, ['class' => 'custom-control-input', 'id' => 'eve_status']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="eve_status"></label>
                        </div>
                    </div>
                </div>                
                <!-- /.card-body -->
                <div class="row mg-t-20">
                	<div class="col-sm-2 mg-b-10"></div>
                	<div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="action" value="insert">
	                	<button type="reset" class="btn btn-warning mg-r-20">Làm lại</button>
	                    <button type="submit" class="btn btn-primary">Thêm mới</button>
	                </div>
                </div>
            </form>
        </div>
    </section>
</div>

@endsection

@section('JS_FOOTER')
    <script src="{{ asset('/assets/ckeditorStandard/ckeditor.js') }}"></script>    
    <script>
    CKEDITOR.replace( 'editor1', {
        filebrowserBrowseUrl: '{{ route('ckfinder_browser') }}',
    } );
    </script>
    @include('ckfinder::setup')
    
    <script type="text/javascript">
        var urlUpload = '{{ route("admin.event.create.upload")}}';
    </script>
    <script>
    $(function() {
        $('.frm_select_2').select2();
        $(".select_type").on('change', function(){
            let id = $(this).val();
            if(id == 41){
                $("#box_show_services").show();
            }else{
                $("#box_show_services").hide();
            }
        });
    });
    </script>
@endsection

resources/views/admin/module/event/edit.blade.php
@extends('admin.layouts') 
@section('CONTAINER')


<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.event.index')}}">Chiến dịch</a>
      <span class="breadcrumb-item active">Sửa</span>
    </nav>
</div>
<div class="br-pagetitle">
    <h4>Sửa Event: {{ $Event['eve_title'] }}</h4>
</div>

<div class="br-pagebody">
    <section class="listing-container">
        <div class="br-section-wrapper container-fluid">
            @include("admin.error")
            <form role="form" method="post" action="/admin/event/{{ $Event['eve_id'] }}/edit" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputParent">Ngôn ngữ</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::select('lang_id', $arrLang, old('lang_id') ? old('lang_id') : $Event['lang_id'] ?? null, ['class="form-control frm_select_2"']); !!}
                    </div>
                </div>              
                 <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Tiêu đề (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('eve_title', old('eve_title') ? old('eve_title') : $Event['eve_title'] ?? null, ['class' => 'form-control','placeholder' => 'Nhập tiêu đề bài viết']) !!}
                    </div>
                </div>             
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="exampleInputFile">Ảnh đại diện (*)</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="eve_banner" id="eve_banner" value="{{ old('eve_banner') ? old('eve_banner') : $Event['eve_banner'] ?? null  }}">
                        @component('admin.upload', ['id_upload' => 'gallery_upload_file', 'type_upload' => 'event', 'max_upload' => 10, 'multiple' => true ,'item_upload' => 'eve_banner', 'name_data' => 'picture_data'])
                        @endcomponent
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Mô tả ngắn</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('eve_intro', old('eve_intro') ? old('eve_intro') : $Event['eve_intro'] ?? null, ['class' => 'form-control','placeholder' => 'Nhập từ mô tả','style="height:100px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Tags</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('eve_tags', old('eve_tags') ? old('eve_tags') : $Event['eve_tags'] ?? null, ['class' => 'form-control','placeholder' => 'Từ khóa: Từ khóa 1| Từ khóa 2| Từ khóa 3','style="height:120px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Form Download</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('eve_form_apply', old('eve_form_apply') ? old('eve_form_apply') : $Event['eve_form_apply'] ?? null, ['class' => 'form-control','placeholder' => 'Link form download','style="height:120px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Nội dung (*)</label>
                    <div class="col-sm-10 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('eve_description', old('eve_description') ? old('eve_description') : $Event['eve_description'] ?? null, ['class' => 'form-control','id' => 'editor1','rows="3"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Thứ tự</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::text('eve_order', old('eve_order') ? old('eve_order') : $Event['eve_order'] ?? null, ['class' => 'form-control','placeholder' => '0']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label" for="InputUsername">Video</label>
                     <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        {!! Form::textarea('eve_video_url', old('eve_video_url') ? old('eve_video_url') : $Event['eve_video_url'] ?? null, ['class' => 'form-control','placeholder' => 'Video youtube','style="height:100px;"']) !!}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 form-control-label">Kích hoạt</label>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <div class="custom-control custom-checkbox">
                            {!! Form::checkbox('eve_status', '1', $Event['eve_status'] ? true : false, ['class' => 'custom-control-input', 'id' => 'eve_status']) !!}
                            <label class="col-sm-4 form-control-label custom-control-label" for="eve_status"></label>
                        </div>
                    </div>
                </div>  
                
                <!-- /.card-body -->
                <div class="row mg-t-20">
                    <div class="col-sm-2 mg-b-10"></div>
                    <div class="col-sm-5 mg-b-10 mg-sm-b-10">
                        <input type="hidden" name="action" value="update">
                        <button type="reset" class="btn btn-warning mg-r-20">Làm lại</button>
                        <button type="submit" class="btn btn-primary">Lưu</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
</div>

@endsection

@section('JS_FOOTER')
<script src="{{ asset('/assets/ckeditorStandard/ckeditor.js') }}"></script>    
<script>
CKEDITOR.replace( 'editor1', {
    filebrowserBrowseUrl: '{{ route('ckfinder_browser') }}',
} );
</script>
@include('ckfinder::setup')

<script type="text/javascript">
    var urlUpload = '{{ route("admin.event.create.upload")}}';
</script>
<script>
$(function() {
    $('.frm_select_2').select2();
    $(".select_type").on('change', function(){
        let id = $(this).val();
        if(id == 41){
            $("#box_show_services").show();
        }else{
            $("#box_show_services").hide();
        }
    }); 
});
</script>
@endsection

resources/views/admin/module/event/list.blade.php
@extends('admin.layouts')
@section('CONTAINER')
<style type="text/css">
	.listing-container .fa-check-square, .fa-square{
		cursor: pointer;
	}
</style>
<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.news.index')}}">Sự kiện</a>
      <span class="breadcrumb-item active">Danh sách</span>
    </nav>
</div>
<div class="br-pagetitle">
	<h4>Danh sách</h4>
</div>

<div class="br-pagebody">
	<section class="listing-container">
        <div class="br-section-wrapper container-fluid">
			<h6 class="br-section-label">Tìm kiếm</h6>
  	  		<form method="GET" action="{{ $page_filter_url }}">
  	  			<div class="row">
		            <div class="col-lg">
		              <input class="form-control" name="eve_title" placeholder="Tiêu đề" type="text" value="{{ isset($params['eve_title']) ? $params['eve_title'] : '' }}">
		            </div>
		            <div class="col-lg">
		              <select  class="form-control" name="lang_id" >
		              	<option value="-1">=Ngôn ngữ=</option>
		              	@foreach($arrLang as $key => $value)
		              		<option {{ (isset($params['lang_id']) && $params['lang_id'] == $key) ? 'selected' : '' }}  value="{{$key}}">{{$value}}</option>
		              	@endforeach
		              </select>
		            </div> 
		            <div class="col-lg">
		              <select  class="form-control" name="eve_status" >
		              	<option value="-1">=Trạng thái=</option>
		              	@foreach($arrStatus as $key => $value)
		              		<option {{ (isset($params['eve_status']) && $params['eve_status'] == $key) ? 'selected' : '' }}  value="{{$key}}">{{$value}}</option>
		              	@endforeach
		              </select>
		            </div>
		            <div class="col-lg-2 mg-t-10 mg-lg-t-0">
		            	<button class="btn btn-primary btn-block mg-b-10"><i class="fa fa-send mg-r-10"></i>Search</button>
		            </div>
		        </div>
  	    	</form>


		  	<div class="bd rounded table-responsive">	
		  	  	<table class="table table-bordered table-striped mg-b-0">
		  	  		<tbody class="">
		                <tr class="thead-colored thead-light">
				          	<td>ID</td>
				          	<td>Tiêu đề</td>
				          	<td class="text-center">Ảnh</td> 
				          	<td class="text-center">Ngày tạo</td>
				          	<td class="text-center">Thứ tự</td>
				          	<td class="text-center">Trạng thái</td>
				          	<td class="text-center">Action</td>
				        </tr>
				      	@foreach ($Events as $keys => $event)
					      	<tr>
							   <td>{{ ++$keys + ($page-1)*15 }}</td>
					           <td>
					           		<p>{{ $event['eve_title'] }}</p>
					           		<p>Người tạo: <b>{{ $arrUser[$event['admin_id']] ?? 'admin' }}</b></p>
					           </td>
					           <td class="text-center"><img width="100px" src="{{ $event['eve_banner'] }}"></td>					            
					           <td class="text-center">{{ date('H:i:s d/m/Y', $event['eve_created_date'])  }}</td>					           
					           <td>
		            			<input class="form-control text-center order_by" idata="{{$event['eve_id']}}" style="width: 75px; margin: auto;" type="text" value="{{ $event['eve_order'] }}">
		            			</td>
					           <td class="text-center">
					           		<b>
					            	@if($event['eve_status'] <= 0)
					            		Đợi duyệt
					            	@elseif($event['eve_status'] == 2)
					            		Không duyệt
					            	@elseif($event['eve_status'] == 1)
					            		Đã duyệt
					            	@endif
					            	</b>
					           </td>
					           <td class="text-center">
					           		<p><a href="{{ route('admin.event.edit', ['id' => $event['eve_id']])  }}"><i class="fas fa-edit"></i> Sửa</a></p>
					           		{!! Form::open(['url' => '/admin/event/'. $event['eve_id'].'/delete' , 'method' => 'GET', 'onsubmit' => 'return confirm("Bạn có chắc chắn muốn xóa bản ghi này?")']); !!}
						          		<button type="submit" class="button-delete" style="cursor: pointer;"><i class="fa fa-times-circle"></i> Xóa</button>
					          		{!! Form::close() !!}					          		
					           </td>
							</tr>
				      	@endforeach
		      		</tbody>
		  	  	</table>
            </div>
            <br/>
            {!! $Events->appends($params)->render() !!}
        </div>
    </section>

</div>
@endsection

@section("JS_FOOTER")
<script type="text/javascript">
	$(function() {	
		$(".order_by").on('change',function(){
			let id = $(this).attr('idata');
			let val = $(this).val();

			/*Update orrder*/
			$.ajax({
				url: '{{ route('api.change_order.eventChangeOrder') }}',
				type: 'POST',
				dataType: 'JSON',
				data: {id:id, value:val},
				success: function(data){
					if(data.status == 0){
						console.log('success');
					}
				}
			});			
		});
	});
</script>
@endsection